### Q1 - Pandas version

In [48]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.5'

# Import and Read Data

In [5]:
car_fuel = pd.read_csv("car_fuel_efficiency_2026.csv")

In [8]:
car_fuel.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

### Q2 - Records Count

In [7]:
car_fuel.shape[0]

10000

### Q3 - Fuel Types

In [9]:
car_fuel["fuel_type"].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

### Q4 - Missing values

In [10]:
car_fuel.isna().any()

model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors              False
engine_displacement    False
num_cylinders          False
horsepower              True
vehicle_weight         False
acceleration            True
fuel_efficiency_mpg    False
dtype: bool

### Q5 - Max fuel efficiency

In [19]:
car_fuel[car_fuel["origin"]  == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

### Q6 - Median value of horsepower

In [32]:
car_fuel["horsepower"].median()

np.float64(252.0)

In [28]:
car_fuel["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [22]:
car_fuel["horsepower"].isna().sum()

np.int64(877)

In [30]:
car_fuel["horsepower"] = car_fuel["horsepower"].fillna(car_fuel["horsepower"].mode()[0])

In [31]:
car_fuel["horsepower"].isna().sum()

np.int64(0)

In [33]:
car_fuel["horsepower"].median()

np.float64(252.0)

### Q7 - Sum of weights

In [37]:
asia_cars = car_fuel[car_fuel['origin'] == 'Asia']

In [38]:
asia_cars.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [40]:
asia_cars[['vehicle_weight','model_year']]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [44]:
vehcile_model = asia_cars[['vehicle_weight','model_year']].reset_index(drop=True).head(7)
print(vehcile_model)

   vehicle_weight  model_year
0            4240        1996
1            4310        1992
2            4230        1997
3            4420        1978
4            3950        2007
5            4750        2021
6            4450        2019

In [46]:
X = vehcile_model.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [47]:
XTX = X.T @ X
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [50]:
X_inv = np.linalg.inv(XTX)
print(X_inv)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [51]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [58]:
inv_T = X_inv @ X.T
print(inv_T)

[[-2.50082897e-04 -1.65786806e-05 -2.86196661e-04  3.99964853e-04
  -1.18162927e-03  1.10298508e-03  2.25354894e-04]
 [ 6.12974614e-04  1.06954785e-04  6.91249245e-04 -7.95968736e-04
   2.63152339e-03 -2.31749941e-03 -4.16221392e-04]]

In [59]:
w =  inv_T @ y 
print(w)

[0.13644777 0.2327492 ]

In [60]:
w.sum()

np.float64(0.36919696904925486)